first: default

addattributecommand: AddAttributeCommand/makefile FORCE
	cd AddAttributeCommand && make

addattributecommand_install: 
	cd AddAttributeCommand && make install
	
addattributecommand_clean:
	cd AddAttributeCommand && make clean

changevaluecommand: ChangeValueCommand/makefile FORCE
	cd ChangeValueCommand && make

changevaluecommand_install:
	cd ChangeValueCommand && make install
	
changevaluecommand_clean:
	cd ChangeValueCommand && make clean

copycommand: CopyCommand/makefile FORCE
	cd CopyCommand && make

copycommand_install:
	cd CopyCommand && make install

copycommand_clean:
	cd CopyCommand && make clean

deletecommand: DeleteCommand/makefile FORCE
	cd DeleteCommand && make

deletecommand_install:
	cd DeleteCommand && make install
	
deletecommand_clean:
	cd DeleteCommand && make clean

findcommand: FindCommand/makefile FORCE
	cd FindCommand && make

findcommand_install:
	cd FindCommand && make install
	
findcommand_clean:
	cd FindCommand && make clean

freemindtranslator: FreeMindTranslator/makefile FORCE
	cd FreeMindTranslator && make

freemindtranslator_install:
	cd FreeMindTranslator && make install
	
freemindtranslator_clean:
	cd FreeMindTranslator && make clean

grapheditor: GraphEditor/makefile FORCE
	cd GraphEditor && make

grapheditor_install:
	cd GraphEditor && make install

grapheditor_clean:
	cd GraphEditor && make clean

groupcommand: GroupCommand/makefile FORCE
	cd GroupCommand && make

groupcommand_install:
	cd GroupCommand && make install
	
groupcommand_clean:
	cd GroupCommand && make clean

insertcommand: InsertCommand/makefile FORCE
	cd InsertCommand && make

insertcommand_install:
	cd InsertCommand && make install
	
insertcommand_clean:
	cd InsertCommand && make clean

movecommand: MoveCommand/makefile FORCE
	cd MoveCommand && make

movecommand_install:
	cd MoveCommand && make install

movecommand_clean:
	cd MoveCommand && make clean

navigatoreditor: NavigatorEditor/makefile FORCE
	cd NavigatorEditor && make

navigatoreditor_install:
	cd NavigatorEditor && make install

navigatoreditor_clean:
	cd NavigatorEditor && make clean

pastecommand: PasteCommand/makefile FORCE
	cd PasteCommand && make

pastecommand_install:
	cd PasteCommand && make install

pastecommand_clean:
	cd PasteCommand && make clean

removeattributecommand: RemoveAttributeCommand/makefile FORCE
	cd RemoveAttributeCommand && make

removeattributecommand_install:
	cd RemoveAttributeCommand && make install

removeattributecommand_clean:
	cd RemoveAttributeCommand && make clean

resizecommand: ResizeCommand/makefile FORCE
	cd ResizeCommand && make

resizecommand_install:
	cd ResizeCommand && make install
	
resizecommand_clean:
	cd ResizeCommand && make clean

selectcommand: SelectCommand/makefile FORCE
	cd SelectCommand && make

selectcommand_install:
	cd SelectCommand && make install

selectcommand_clean:
	cd SelectCommand && make clean

standardtranslator: StandardTranslator/makefile FORCE
	cd StandardTranslator && make

standardtranslator_install:
	cd StandardTranslator && make install
	
standardtranslator_clean:
	cd StandardTranslator && make clean
	

default: \
	addattributecommand \
	changevaluecommand \
	copycommand \
	deletecommand \
	findcommand \
	freemindtranslator \
	grapheditor \
	groupcommand \
	insertcommand \
	movecommand \
	navigatoreditor \
	pastecommand \
	removeattributecommand \
	resizecommand \
	selectcommand \
	standardtranslator

clean: \
	addattributecommand_clean \
	changevaluecommand_clean \
	copycommand_clean \
	deletecommand_clean \
	findcommand_clean \
	freemindtranslator_clean \
	grapheditor_clean \
	groupcommand_clean \
	insertcommand_clean \
	movecommand_clean \
	navigatoreditor_clean \
	pastecommand_clean \
	removeattributecommand_clean \
	resizecommand_clean \
	selectcommand_clean \
	standardtranslator_clean
	
install: \
	addattributecommand_install \
	changevaluecommand_install \
	copycommand_install \
	deletecommand_clean \
	findcommand_clean \
	freemindtranslator_install \
	grapheditor_install \
	groupcommand_install \
	insertcommand_install \
	movecommand_install \
	navigatoreditor_install \
	pastecommand_install \
	removeattributecommand_install \
	resizecommand_install \
	selectcommand_install \
	standardtranslator_install

FORCE:
